name: Monitor Render Server

permissions:
  contents: write  # ensure write permission to push commits

on:
  schedule:
    - cron: '*/1 * * * *'  # every 1 minute (UTC)
  workflow_dispatch:

jobs:
  check-render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check /uptime endpoint
        id: ping
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 65 https://main-backend-b3ak.onrender.com/uptime)
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            STATUS="timeout"
          else
            STATUS="$RESPONSE"
          fi
          echo "STATUS=$STATUS" >> $GITHUB_ENV
          echo "Server returned HTTP status: $STATUS"

      - name: Update status.json
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "{\"status\":\"$STATUS\",\"timestamp\":\"$TIMESTAMP\"}" > status.json
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Commit and push status.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add status.json
          git diff --cached --quiet || git commit -m "Update status.json: status=$STATUS at $TIMESTAMP"

          # Use token to authenticate push
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main

      - name: Log success message
        if: env.STATUS == '200'
        run: echo "✅ Render server is UP and responded with 200 OK"

      - name: Send Telegram alert if down or timeout
        if: env.STATUS != '200'
        run: |
          curl -s "https://api.telegram.org/bot7912010445:AAH8DivQSTW8PrN6N9hNXpDj2WdG5DVXAaI/sendMessage?chat_id=807564728&text=🚨+Render+StudyProtocol+Server+Not+Responding+or+Timed+Out+(Status:+$STATUS)"
